### ISSUE TITLE
Response Eval down the json tree

### ISSUE THREAD

**Issue by herrigor** [taylorgoolsby/insomnia-plugin-response-eval#8]
I'm trying to do a reduce on the nodes from a Request and traverse down the json tree like `output.data.equipment`, but I can only get up to the `output` to work. I need somthing pretty much liken the native `Response ⇒ Body Attribute` works.
I tried `output.data`, `$.data` and `JSON.parse()`

This is my object
`{
   "data":{
      "equipment":{
         "count":2,
         "edges":[
            {
               "node":{
                  "macAddress":"ABCD1"
               }
            },
            {
               "node":{
                  "macAddress":"EFGH2"
               }
            },
         ]
      }
   }
}`
and I need to do this:
`json.data.equipment.edges.reduce((acc, node)=>{
    acc.push(node.node.macAddress);
    return acc;
},[]);`

How can I come about it? Can I?

**Comment by taylorgoolsby** [comment]
You need to parse the output first. `output` is holding a string representation of your json object.

This should work: `JSON.parse(output).data.equipment.edges.reduce((acc, node)=>{ acc.push(node.node.macAddress); return acc; },[]);`

I have tried something very similar on my own graphql API, and can confirm the above works.
